version: '3.8'

services:
  app:
    #build: .
    image: registry.cn-hangzhou.aliyuncs.com/panxf/cmc-privacy:1.0.3
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app
      - /var/run/tappd.sock:/var/run/tappd.sock
    environment:
      - NODE_ENV=development
      - AWS_ACCESS_KEY_ID=81KECAWHJA0L5QPMEU65
      - AWS_SECRET_ACCESS_KEY=CuGnTZk2izqy9nmc+nJBl6MJpT8do+Wlv3hA84Rr
      - S3_BUCKET=newbridge1
      - DSTACK_SIMULATOR_ENDPOINT=http://10.207.20.56:8090 
    restart: always